# Generated by Django 4.2.11 on 2026-08-15 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evidence', '0002_rls'),
        ('organizations', '0003_seed_senegal_country_pack'),
        ('programs', '0003_seed_senegal_milestone_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('outcome', models.CharField(choices=[('conforme', 'Conforme'), ('avec_reserve', 'Avec réserve')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='evidence.evidence')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='programs.lot')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='organizations.organization')),
            ],
            options={
                'db_table': 'inspections_inspection',
            },
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reserves', to='programs.lot')),
                ('opened_by_inspection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_reserve', to='inspections.inspection')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserves', to='organizations.organization')),
            ],
            options={
                'db_table': 'inspections_reserve',
            },
        ),
        migrations.CreateModel(
            name='ReserveCorrection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reserve_corrections', to='evidence.evidence')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserve_corrections', to='organizations.organization')),
                ('reserve', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='inspections.reserve')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reserve_corrections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inspections_reserve_correction',
            },
        ),
        migrations.AddField(
            model_name='inspection',
            name='reserve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='follow_up_inspections', to='inspections.reserve'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='work_declaration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='evidence.workdeclaration'),
        ),
        migrations.AddConstraint(
            model_name='inspection',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('evidence__isnull', True), ('work_declaration__isnull', False)), models.Q(('evidence__isnull', False), ('work_declaration__isnull', True)), _connector='OR'), name='inspection_exactly_one_subject'),
        ),
    ]
