# Generated by Django 4.2.11 on 2026-08-15 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_rls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='opened_by_inspection',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='opened_reserve', to='inspections.inspection'),
        ),
    ]
