# Generated by Django 4.2.11 on 2026-08-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0003_alter_reserve_opened_by_inspection'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='client_correlation_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
