# Generated by Django 4.2.11 on 2026-08-16 00:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_seed_senegal_country_pack'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evidence', '0002_rls'),
        ('inspections', '0004_inspection_client_correlation_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionMission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='missions_assigned_by', to=settings.AUTH_USER_MODEL)),
                ('assigned_inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_missions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_missions', to='organizations.organization')),
                ('work_declaration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspection_missions', to='evidence.workdeclaration')),
            ],
            options={
                'db_table': 'inspections_mission',
            },
        ),
    ]
