# Generated by Django 4.2.11 on 2026-09-27 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inspections", "0006_inspectionmission_rls"),
    ]

    operations = [
        migrations.AddField(
            model_name="inspection",
            name="examined_evidence_ids",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="inspection",
            name="reserve_decisions",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="reserve",
            name="expected_action",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="reserve",
            name="motif",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="reserve",
            name="opened_by_inspection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="opened_reserves",
                to="inspections.inspection",
            ),
        ),
    ]
