# Generated by Django 4.2.11 on 2026-08-19 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('programs', '0006_lot_assigned_organization'),
        ('organizations', '0003_seed_senegal_country_pack'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate_organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devis_submitted', to='organizations.organization')),
                ('logged_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devis_logged', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devis_set', to='programs.lot')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devis_received', to='organizations.organization')),
            ],
            options={
                'db_table': 'procurement_devis',
            },
        ),
    ]
