# Generated by Django 4.2.11 on 2026-08-19 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_seed_senegal_country_pack'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canal', models.CharField(choices=[('canal_1_marge', 'Marge (canal 1)'), ('canal_2_commission', 'Commission (canal 2)')], max_length=30)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country_pack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pricing_configs', to='organizations.countrypack')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pricing_configs_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pricing_pricingconfig',
            },
        ),
    ]
