# Generated by Django 4.2.11 on 2026-08-19 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0003_seed_senegal_country_pack'),
        ('pricing', '0002_pricingconfig_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalPaymentTierTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legal_payment_tier_templates_activated', to=settings.AUTH_USER_MODEL)),
                ('country_pack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legal_payment_tier_templates', to='organizations.countrypack')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legal_payment_tier_templates_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pricing_legal_payment_tier_template',
            },
        ),
        migrations.CreateModel(
            name='LegalPaymentTierStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField()),
                ('code', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('cumulative_cap_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('allows_progressive_payments', models.BooleanField()),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='pricing.legalpaymenttiertemplate')),
            ],
            options={
                'db_table': 'pricing_legal_payment_tier_step',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ActiveLegalPaymentTierTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country_pack', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='active_legal_payment_tier_template', to='organizations.countrypack')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='active_pointers', to='pricing.legalpaymenttiertemplate')),
            ],
            options={
                'db_table': 'pricing_active_legal_payment_tier_template',
            },
        ),
        migrations.AddConstraint(
            model_name='legalpaymenttiertemplate',
            constraint=models.UniqueConstraint(fields=('country_pack', 'version'), name='unique_tier_template_version_per_country_pack'),
        ),
        migrations.AddConstraint(
            model_name='legalpaymenttierstep',
            constraint=models.UniqueConstraint(fields=('template', 'order'), name='unique_tier_step_order_per_template'),
        ),
        migrations.AddConstraint(
            model_name='legalpaymenttierstep',
            constraint=models.UniqueConstraint(fields=('template', 'code'), name='unique_tier_step_code_per_template'),
        ),
    ]
