# Generated by Django 4.2.11 on 2026-08-20 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0003_seed_senegal_country_pack'),
        ('pricing', '0005_pricingconfig_sequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlOfficeRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jalon_type', models.CharField(max_length=50)),
                ('calculation_mode', models.CharField(choices=[('percentage', 'Pourcentage du coût de construction'), ('fixed_amount', 'Montant fixe')], max_length=20)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sequence', models.BigIntegerField(editable=False, unique=True)),
                ('country_pack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='control_office_rates', to='organizations.countrypack')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='control_office_rates_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pricing_control_office_rate',
            },
        ),
        migrations.AddConstraint(
            model_name='controlofficerate',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('calculation_mode', 'percentage'), ('fixed_amount__isnull', True), ('percentage__isnull', False)), models.Q(('calculation_mode', 'fixed_amount'), ('fixed_amount__isnull', False), ('percentage__isnull', True)), _connector='OR'), name='control_office_rate_exactly_one_value_active'),
        ),
    ]
