# Generated by Django 4.2.11 on 2026-09-28 05:52

from django.db import migrations, models

# Audit UI R1, PO-2026-09-28-03. Les paliers existants ne sont jamais
# réécrits (verrou d'immutabilité, migration 0004) : ils prennent la valeur
# par défaut ; le premier palier n'est de toute façon jamais conditionné
# (apps.sales.services.compute_payment_call_candidates). Le barème de
# démonstration avec la règle explicite est publié en NOUVELLE version
# (`seed_demo_payment_tiers --new-version`).


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0007_controlofficerate_sequence_and_rls"),
    ]

    operations = [
        migrations.AddField(
            model_name="legalpaymenttierstep",
            name="requires_technical_acceptance",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="legalpaymenttiertemplate",
            name="legally_validated",
            field=models.BooleanField(default=False),
        ),
    ]
