# Generated by Django 4.2.11 on 2026-09-29 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecosystem_core", "0001_demo_instance"),
    ]

    operations = [
        migrations.AddField(
            model_name="demoinstance",
            name="program_ids",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
