# Generated by Django 4.2.11 on 2026-08-15 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0003_seed_senegal_country_pack'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_id', models.UUIDField()),
                ('level', models.CharField(choices=[('declare', 'Déclaré'), ('documente', 'Documenté'), ('controle', 'Contrôlé'), ('verifie', 'Vérifié'), ('valide', 'Validé')], max_length=20)),
                ('source', models.CharField(max_length=100)),
                ('scope', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trust_events', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trust_events', to='organizations.organization')),
                ('previous_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='trust.trustevent')),
                ('subject_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'trust_event',
                'indexes': [models.Index(fields=['subject_type', 'subject_id'], name='trust_event_subject_7394fa_idx')],
            },
        ),
    ]
