# Generated by Django 4.2.11 on 2026-08-15 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_seed_senegal_country_pack'),
        ('trust', '0002_append_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trustevent',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trust_events', to='organizations.organization'),
        ),
    ]
