# Generated by Django 4.2.11 on 2026-08-15 11:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_seed_senegal_country_pack'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='organizations.organization')),
            ],
            options={
                'db_table': 'programs_asset',
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='programs.asset')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='organizations.organization')),
            ],
            options={
                'db_table': 'programs_lot',
            },
        ),
        migrations.CreateModel(
            name='MilestoneTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country_pack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='milestone_templates', to='organizations.countrypack')),
            ],
            options={
                'db_table': 'programs_milestone_template',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='organizations.organization')),
            ],
            options={
                'db_table': 'programs_program',
            },
        ),
        migrations.CreateModel(
            name='MilestoneTemplateStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField()),
                ('code', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='programs.milestonetemplate')),
            ],
            options={
                'db_table': 'programs_milestone_template_step',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField()),
                ('code', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='programs.lot')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='organizations.organization')),
            ],
            options={
                'db_table': 'programs_milestone',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='programs.program'),
        ),
        migrations.AddConstraint(
            model_name='milestonetemplatestep',
            constraint=models.UniqueConstraint(fields=('template', 'order'), name='unique_step_order_per_template'),
        ),
        migrations.AddConstraint(
            model_name='milestonetemplatestep',
            constraint=models.UniqueConstraint(fields=('template', 'code'), name='unique_step_code_per_template'),
        ),
        migrations.AddConstraint(
            model_name='milestonetemplate',
            constraint=models.UniqueConstraint(fields=('country_pack', 'version'), name='unique_template_version_per_country_pack'),
        ),
        migrations.AddConstraint(
            model_name='milestone',
            constraint=models.UniqueConstraint(fields=('lot', 'order'), name='unique_milestone_order_per_lot'),
        ),
    ]
