# Generated by Django 4.2.11 on 2026-08-15 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0003_seed_senegal_country_pack"),
        ("programs", "0003_seed_senegal_milestone_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="location",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name="LotClient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_lots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_assignments",
                        to="programs.lot",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lot_clients",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "programs_lot_client",
            },
        ),
        migrations.AddConstraint(
            model_name="lotclient",
            constraint=models.UniqueConstraint(
                fields=("lot", "client"), name="unique_client_per_lot"
            ),
        ),
    ]
