# Generated by Django 4.2.11 on 2026-08-15 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0003_seed_senegal_country_pack"),
        ("programs", "0005_lot_client_rls"),
    ]

    operations = [
        migrations.AddField(
            model_name="lot",
            name="assigned_organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assigned_lots",
                to="organizations.organization",
            ),
        ),
    ]
