# Generated by Django 4.2.11 on 2026-08-20 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_seed_senegal_country_pack'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('programs', '0006_lot_assigned_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='lot',
            name='surface',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='ProgramCost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('foncier_total', models.DecimalField(decimal_places=2, max_digits=16)),
                ('be_total', models.DecimalField(decimal_places=2, max_digits=16)),
                ('repartition_method', models.CharField(choices=[('prorata_surface', 'Prorata surface'), ('parts_egales', 'Parts égales')], max_length=30)),
                ('justification', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sequence', models.BigIntegerField(editable=False, unique=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='program_costs_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_costs', to='organizations.organization')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='costs', to='programs.program')),
            ],
            options={
                'db_table': 'programs_program_cost',
            },
        ),
    ]
