# Generated by Django 4.2.11 on 2026-08-23 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0003_seed_senegal_country_pack"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("programs", "0009_lot_admin_keyimmo_select"),
    ]

    operations = [
        migrations.AddField(
            model_name="lot",
            name="commercial_status",
            field=models.CharField(
                choices=[
                    ("disponible", "Disponible"),
                    ("reserve", "Réservé"),
                    ("vendu", "Vendu"),
                ],
                default="disponible",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="lot",
            name="sale_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=16, null=True
            ),
        ),
        migrations.CreateModel(
            name="ProgramRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("acceptee", "Acceptée"),
                            ("refusee", "Refusée"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="program_requests",
                        to="organizations.organization",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_requests",
                        to="programs.program",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="program_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "programs_program_request",
            },
        ),
    ]
