# Generated by Django 4.2.11 on 2026-09-27 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ecosystem_core", "0001_demo_instance"),
        ("programs", "0011_program_request_rls"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="demo_instance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programs",
                to="ecosystem_core.demoinstance",
            ),
        ),
    ]
