# Generated by Django 4.2.11 on 2026-09-28 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0012_program_demo_instance"),
    ]

    operations = [
        migrations.AddField(
            model_name="milestone",
            name="required_pieces",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="milestonetemplatestep",
            name="required_pieces",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
