# Generated by Django 4.2.11 on 2026-08-15 12:02

import apps.evidence.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0003_seed_senegal_country_pack'),
        ('programs', '0003_seed_senegal_milestone_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('visibility', models.CharField(choices=[('interne', 'Interne'), ('client', 'Client'), ('public', 'Public')], default='interne', max_length=20)),
                ('sensitivity_level', models.CharField(choices=[('public', 'Public'), ('interne', 'Interne'), ('confidentiel', 'Confidentiel')], default='interne', max_length=20)),
                ('hash', models.CharField(editable=False, max_length=64)),
                ('version', models.PositiveIntegerField(default=1)),
                ('file', models.FileField(upload_to=apps.evidence.models._document_upload_path)),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to=apps.evidence.models._thumbnail_upload_path)),
                ('source', models.CharField(max_length=100)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='organizations.organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'evidence_document',
            },
        ),
        migrations.CreateModel(
            name='WorkDeclaration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('declared_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_declarations', to=settings.AUTH_USER_MODEL)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_declarations', to='programs.milestone')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_declarations', to='organizations.organization')),
            ],
            options={
                'db_table': 'evidence_work_declaration',
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidences', to=settings.AUTH_USER_MODEL)),
                ('documents', models.ManyToManyField(related_name='evidences', to='evidence.document')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='organizations.organization')),
                ('work_declaration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidences', to='evidence.workdeclaration')),
            ],
            options={
                'db_table': 'evidence_evidence',
            },
        ),
    ]
