# Generated by Django 4.2.11 on 2026-08-23 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("evidence", "0002_rls"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="duplicate_of",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="duplicates",
                to="evidence.document",
            ),
        ),
    ]
