# Generated by Django 4.2.11 on 2026-09-28 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evidence", "0003_document_duplicate_of"),
    ]

    operations = [
        migrations.AddField(
            model_name="evidence",
            name="required_piece",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
