# Generated by Django 4.2.11 on 2026-08-15 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0003_seed_senegal_country_pack'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('programs', '0003_seed_senegal_milestone_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('task', 'Tâche'), ('notification', 'Notification'), ('alert', 'Alerte'), ('exception', 'Exception')], max_length=20)),
                ('subject_id', models.UUIDField()),
                ('source', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Faible'), ('normal', 'Normale'), ('high', 'Haute')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('done', 'Traitée')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='organizations.organization')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='programs.program')),
                ('subject_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'tasks_task',
                'indexes': [models.Index(fields=['assignee', 'status'], name='tasks_task_assigne_7928f6_idx')],
            },
        ),
    ]
