# Generated by Django 4.2.11 on 2026-08-19 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox_tasks', '0002_rls'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('subject_type', 'subject_id', 'source'), name='unique_task_per_subject_and_source'),
        ),
    ]
