# Generated by Django 4.2.11 on 2026-09-27 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0003_seed_senegal_country_pack"),
        ("programs", "0011_program_request_rls"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Demandée"),
                            ("held", "Bloquée"),
                            ("reserved", "Réservée"),
                            ("committed", "Concrétisée"),
                            ("expired", "Expirée"),
                            ("cancelled", "Annulée"),
                        ],
                        max_length=20,
                    ),
                ),
                ("held_until", models.DateTimeField()),
                ("price_amount", models.DecimalField(decimal_places=2, max_digits=16)),
                ("currency", models.CharField(default="XOF", max_length=3)),
                ("cancellation_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cancelled_reservations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="programs.lot",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "sales_reservation",
            },
        ),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["held", "reserved", "committed"])),
                fields=("lot",),
                name="sales_one_blocking_reservation_per_lot",
            ),
        ),
    ]
