# Generated by Django 4.2.11 on 2026-09-27 02:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0003_seed_senegal_country_pack"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sales", "0002_reservation_rls"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("review", "En revue"),
                            ("approved", "Approuvé"),
                            ("signed_simulated", "Signé (simulation)"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("signed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_contract_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "authored_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="authored_contract_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contract_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contract_versions",
                        to="organizations.organization",
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contract_versions",
                        to="sales.reservation",
                    ),
                ),
            ],
            options={
                "db_table": "sales_contract_version",
            },
        ),
        migrations.AddConstraint(
            model_name="contractversion",
            constraint=models.UniqueConstraint(
                fields=("reservation", "version"), name="sales_contract_unique_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="contractversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["draft", "review"])),
                fields=("reservation",),
                name="sales_contract_one_version_in_progress",
            ),
        ),
    ]
