# Generated by Django 4.2.11 on 2026-09-27 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0003_seed_senegal_country_pack"),
        ("pricing", "0007_controlofficerate_sequence_and_rls"),
        ("sales", "0004_contractversion_rls_and_guard"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentCall",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("frais", "Frais de réservation"),
                            ("premier_versement", "Complément du premier versement"),
                            ("versement", "Versement de palier"),
                        ],
                        max_length=20,
                    ),
                ),
                ("tier_code", models.CharField(blank=True, max_length=50)),
                ("tier_label", models.CharField(blank=True, max_length=100)),
                (
                    "cumulative_cap_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=16)),
                ("currency", models.CharField(default="XOF", max_length=3)),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_calls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issued_payment_calls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "legal_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_calls",
                        to="pricing.legalpaymenttiertemplate",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_calls",
                        to="organizations.organization",
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_calls",
                        to="sales.reservation",
                    ),
                ),
            ],
            options={
                "db_table": "sales_payment_call",
            },
        ),
        migrations.AddConstraint(
            model_name="paymentcall",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind__in", ["frais", "premier_versement"])),
                fields=("reservation", "kind"),
                name="sales_payment_call_once_per_kind",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentcall",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "versement")),
                fields=("reservation", "tier_code"),
                name="sales_payment_call_once_per_tier",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentcall",
            constraint=models.CheckConstraint(
                check=models.Q(("amount__gt", 0)),
                name="sales_payment_call_amount_positive",
            ),
        ),
    ]
