# Generated by Django 4.2.11 on 2026-09-27 03:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0003_seed_senegal_country_pack"),
        ("sales", "0006_paymentcall_rls_append_only"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("bank_reference", models.CharField(max_length=64)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=16)),
                ("currency", models.CharField(default="XOF", max_length=3)),
                ("received_on", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("bank_executed_sim", "Reçu en banque (simulé)"),
                            ("reconciled_sim", "Rapproché (simulé)"),
                        ],
                        default="bank_executed_sim",
                        max_length=20,
                    ),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("reconciled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customer_receipts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customer_receipts",
                        to="organizations.organization",
                    ),
                ),
                (
                    "reconciled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reconciled_customer_receipts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recorded_customer_receipts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipts",
                        to="sales.reservation",
                    ),
                ),
            ],
            options={
                "db_table": "sales_customer_receipt",
            },
        ),
        migrations.CreateModel(
            name="Allocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "allocated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recorded_allocations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="organizations.organization",
                    ),
                ),
                (
                    "payment_call",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="sales.paymentcall",
                    ),
                ),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="sales.customerreceipt",
                    ),
                ),
            ],
            options={
                "db_table": "sales_allocation",
            },
        ),
        migrations.AddConstraint(
            model_name="customerreceipt",
            constraint=models.UniqueConstraint(
                fields=("organization", "bank_reference"),
                name="sales_receipt_unique_bank_reference",
            ),
        ),
        migrations.AddConstraint(
            model_name="customerreceipt",
            constraint=models.CheckConstraint(
                check=models.Q(("amount__gt", 0)), name="sales_receipt_amount_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="allocation",
            constraint=models.CheckConstraint(
                check=models.Q(("amount__gt", 0)),
                name="sales_allocation_amount_positive",
            ),
        ),
    ]
