# Generated by Django 4.2.11 on 2026-09-27 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("programs", "0011_program_request_rls"),
        ("organizations", "0003_seed_senegal_country_pack"),
        ("sales", "0008_receipt_allocation_rls_and_guards"),
    ]

    operations = [
        migrations.CreateModel(
            name="Disbursement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=16)),
                ("currency", models.CharField(default="XOF", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("eligible", "Éligible (montant réservé)"),
                            ("executed_sim", "Exécuté (simulé)"),
                            ("cancelled", "Annulé"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "flow_status",
                    models.CharField(
                        choices=[
                            ("planned", "Prévu"),
                            ("bank_executed_sim", "Exécuté en banque (simulé)"),
                            (
                                "beneficiary_confirmed_sim",
                                "Confirmé par le bénéficiaire (simulé)",
                            ),
                            ("reconciled_sim", "Rapproché (simulé)"),
                        ],
                        default="planned",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("eligible_at", models.DateTimeField(blank=True, null=True)),
                (
                    "bank_reference",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("executed_on", models.DateField(blank=True, null=True)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "beneficiary_confirmed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("reconciled_at", models.DateTimeField(blank=True, null=True)),
                ("reconciliation_reason", models.CharField(blank=True, max_length=255)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancel_reason", models.CharField(blank=True, max_length=255)),
                (
                    "beneficiary_confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="confirmed_disbursements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "beneficiary_organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="received_disbursements",
                        to="organizations.organization",
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cancelled_disbursements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "executed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="executed_disbursements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disbursements",
                        to="programs.lot",
                    ),
                ),
                (
                    "milestone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disbursements",
                        to="programs.milestone",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disbursements",
                        to="organizations.organization",
                    ),
                ),
                (
                    "prepared_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prepared_disbursements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disbursements",
                        to="programs.program",
                    ),
                ),
                (
                    "reconciled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reconciled_disbursements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sales_disbursement",
            },
        ),
        migrations.AddConstraint(
            model_name="disbursement",
            constraint=models.UniqueConstraint(
                fields=("program", "bank_reference"),
                name="sales_disbursement_unique_bank_reference",
            ),
        ),
        migrations.AddConstraint(
            model_name="disbursement",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["draft", "eligible"])),
                fields=("milestone",),
                name="sales_disbursement_one_open_per_milestone",
            ),
        ),
        migrations.AddConstraint(
            model_name="disbursement",
            constraint=models.CheckConstraint(
                check=models.Q(("amount__gt", 0)),
                name="sales_disbursement_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="disbursement",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("status", "executed_sim"), _negated=True),
                    models.Q(
                        ("bank_reference__isnull", False),
                        ("executed_on__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="sales_disbursement_executed_has_bank_proof",
            ),
        ),
        migrations.AddConstraint(
            model_name="disbursement",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("status", "executed_sim"),
                    ("flow_status", "planned"),
                    _connector="OR",
                ),
                name="sales_disbursement_flow_follows_execution",
            ),
        ),
    ]
