# Generated by Django 4.2.11 on 2026-09-27 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0003_seed_senegal_country_pack"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sales", "0010_disbursement_rls_and_guard"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="validated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="validated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="validated_reservations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="PaymentNotice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=16)),
                ("currency", models.CharField(default="XOF", max_length=3)),
                ("client_reference", models.CharField(max_length=64)),
                ("paid_on", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("declared", "Déclaré — en attente de confirmation"),
                            ("confirmed", "Confirmé par Finance"),
                            ("rejected", "Rejeté par Finance"),
                        ],
                        default="declared",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.CharField(blank=True, max_length=255)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_notices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_notices",
                        to="organizations.organization",
                    ),
                ),
                (
                    "payment_call",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_notices",
                        to="sales.paymentcall",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="processed_payment_notices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "receipt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_notices",
                        to="sales.customerreceipt",
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_notices",
                        to="sales.reservation",
                    ),
                ),
            ],
            options={
                "db_table": "sales_payment_notice",
            },
        ),
        migrations.AddConstraint(
            model_name="paymentnotice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "declared")),
                fields=("payment_call",),
                name="sales_one_pending_notice_per_call",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentnotice",
            constraint=models.CheckConstraint(
                check=models.Q(("amount__gt", 0)),
                name="sales_payment_notice_amount_positive",
            ),
        ),
    ]
