# Generated by Django 4.2.11 on 2026-09-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0012_payment_notice_rls_and_guard"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentnotice",
            name="status",
            field=models.CharField(
                choices=[
                    ("declared", "Signalé par le client — non encaissé"),
                    ("confirmed", "Traité — encaissement enregistré"),
                    ("rejected", "Introuvable au relevé (simulé)"),
                ],
                default="declared",
                max_length=20,
            ),
        ),
    ]
