# Generated by Django 4.2.11 on 2026-09-27 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0013_payment_notice_labels_audit_f01"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractversion",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Brouillon"),
                    ("review", "En revue"),
                    ("approved", "Approuvé"),
                    ("signed_simulated", "Signé (simulé)"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="customerreceipt",
            name="status",
            field=models.CharField(
                choices=[
                    ("bank_executed_sim", "Exécuté par la banque (simulé)"),
                    ("reconciled_sim", "Rapproché (simulé)"),
                ],
                default="bank_executed_sim",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="disbursement",
            name="flow_status",
            field=models.CharField(
                choices=[
                    ("planned", "Planifié"),
                    ("bank_executed_sim", "Exécuté par la banque (simulé)"),
                    (
                        "beneficiary_confirmed_sim",
                        "Confirmé par le bénéficiaire (simulé)",
                    ),
                    ("reconciled_sim", "Rapproché (simulé)"),
                ],
                default="planned",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="disbursement",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Brouillon"),
                    ("eligible", "Éligible"),
                    ("executed_sim", "Exécuté (simulé)"),
                    ("cancelled", "Annulé"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("requested", "Demandée"),
                    ("held", "Bien bloqué"),
                    ("reserved", "Réservée"),
                    ("committed", "Concrétisée"),
                    ("expired", "Expirée"),
                    ("cancelled", "Annulée"),
                ],
                max_length=20,
            ),
        ),
    ]
