# Generated by Django 4.2.11 on 2026-09-28 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0014_libelles_design_system"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentnotice",
            name="status",
            field=models.CharField(
                choices=[
                    ("declared", "Signalé par le client — non encaissé"),
                    ("confirmed", "Traité — encaissement enregistré"),
                    ("rejected", "Clôturé sans rattachement"),
                ],
                default="declared",
                max_length=20,
            ),
        ),
    ]
