# Generated by Django 4.2.11 on 2026-09-28 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0015_signalement_cloture"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="ended_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
