# Generated by Django 4.2.11 on 2026-09-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0003_seed_senegal_country_pack"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="role_label",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
    ]
